// Reference catalogs for the supported management system standards.

export interface IsoRef {
  id: string;
  standard: 'ISO 9001' | 'ISO 27001' | 'ISO 37301';
  clause: string;
  title: string;
}

const iso9001: [string, string][] = [
  ['4.1', 'Verstehen der Organisation und ihres Kontextes'],
  ['4.2', 'Erfordernisse und Erwartungen interessierter Parteien'],
  ['4.3', 'Anwendungsbereich des QM-Systems'],
  ['4.4', 'QM-System und seine Prozesse'],
  ['5.1', 'Führung und Verpflichtung'],
  ['5.2', 'Qualitätspolitik'],
  ['5.3', 'Rollen, Verantwortlichkeiten und Befugnisse'],
  ['6.1', 'Maßnahmen zum Umgang mit Risiken und Chancen'],
  ['6.2', 'Qualitätsziele und Planung zu deren Erreichung'],
  ['6.3', 'Planung von Änderungen'],
  ['7.1', 'Ressourcen'],
  ['7.2', 'Kompetenz'],
  ['7.3', 'Bewusstsein'],
  ['7.4', 'Kommunikation'],
  ['7.5', 'Dokumentierte Information'],
  ['8.1', 'Betriebliche Planung und Steuerung'],
  ['8.2', 'Anforderungen an Produkte und Dienstleistungen'],
  ['8.3', 'Entwicklung von Produkten und Dienstleistungen'],
  ['8.4', 'Steuerung extern bereitgestellter Prozesse, Produkte und Dienstleistungen'],
  ['8.5', 'Produktion und Dienstleistungserbringung'],
  ['8.6', 'Freigabe von Produkten und Dienstleistungen'],
  ['8.7', 'Steuerung nichtkonformer Ergebnisse'],
  ['9.1', 'Überwachung, Messung, Analyse und Bewertung'],
  ['9.2', 'Internes Audit'],
  ['9.3', 'Managementbewertung'],
  ['10.2', 'Nichtkonformität und Korrekturmaßnahmen'],
  ['10.3', 'Fortlaufende Verbesserung'],
];

const iso27001: [string, string][] = [
  ['4.1', 'Understanding the organization and its context'],
  ['4.2', 'Needs and expectations of interested parties'],
  ['4.3', 'Scope of the ISMS'],
  ['5.1', 'Leadership and commitment'],
  ['5.2', 'Policy'],
  ['5.3', 'Roles, responsibilities and authorities'],
  ['6.1.2', 'Information security risk assessment'],
  ['6.1.3', 'Information security risk treatment'],
  ['6.2', 'Information security objectives'],
  ['7.2', 'Competence'],
  ['7.3', 'Awareness'],
  ['7.5', 'Documented information'],
  ['8.1', 'Operational planning and control'],
  ['8.2', 'Information security risk assessment (operation)'],
  ['8.3', 'Information security risk treatment (operation)'],
  ['9.1', 'Monitoring, measurement, analysis and evaluation'],
  ['9.2', 'Internal audit'],
  ['9.3', 'Management review'],
  ['10.2', 'Nonconformity and corrective action'],
];

/** ISO/IEC 27001:2022 Annex A – 93 controls */
export const annexA: [string, string][] = [
  ['A.5.1', 'Policies for information security'],
  ['A.5.2', 'Information security roles and responsibilities'],
  ['A.5.3', 'Segregation of duties'],
  ['A.5.4', 'Management responsibilities'],
  ['A.5.5', 'Contact with authorities'],
  ['A.5.6', 'Contact with special interest groups'],
  ['A.5.7', 'Threat intelligence'],
  ['A.5.8', 'Information security in project management'],
  ['A.5.9', 'Inventory of information and other associated assets'],
  ['A.5.10', 'Acceptable use of information and other associated assets'],
  ['A.5.11', 'Return of assets'],
  ['A.5.12', 'Classification of information'],
  ['A.5.13', 'Labelling of information'],
  ['A.5.14', 'Information transfer'],
  ['A.5.15', 'Access control'],
  ['A.5.16', 'Identity management'],
  ['A.5.17', 'Authentication information'],
  ['A.5.18', 'Access rights'],
  ['A.5.19', 'Information security in supplier relationships'],
  ['A.5.20', 'Addressing information security within supplier agreements'],
  ['A.5.21', 'Managing information security in the ICT supply chain'],
  ['A.5.22', 'Monitoring, review and change management of supplier services'],
  ['A.5.23', 'Information security for use of cloud services'],
  ['A.5.24', 'Information security incident management planning and preparation'],
  ['A.5.25', 'Assessment and decision on information security events'],
  ['A.5.26', 'Response to information security incidents'],
  ['A.5.27', 'Learning from information security incidents'],
  ['A.5.28', 'Collection of evidence'],
  ['A.5.29', 'Information security during disruption'],
  ['A.5.30', 'ICT readiness for business continuity'],
  ['A.5.31', 'Legal, statutory, regulatory and contractual requirements'],
  ['A.5.32', 'Intellectual property rights'],
  ['A.5.33', 'Protection of records'],
  ['A.5.34', 'Privacy and protection of PII'],
  ['A.5.35', 'Independent review of information security'],
  ['A.5.36', 'Compliance with policies, rules and standards for information security'],
  ['A.5.37', 'Documented operating procedures'],
  ['A.6.1', 'Screening'],
  ['A.6.2', 'Terms and conditions of employment'],
  ['A.6.3', 'Information security awareness, education and training'],
  ['A.6.4', 'Disciplinary process'],
  ['A.6.5', 'Responsibilities after termination or change of employment'],
  ['A.6.6', 'Confidentiality or non-disclosure agreements'],
  ['A.6.7', 'Remote working'],
  ['A.6.8', 'Information security event reporting'],
  ['A.7.1', 'Physical security perimeters'],
  ['A.7.2', 'Physical entry'],
  ['A.7.3', 'Securing offices, rooms and facilities'],
  ['A.7.4', 'Physical security monitoring'],
  ['A.7.5', 'Protecting against physical and environmental threats'],
  ['A.7.6', 'Working in secure areas'],
  ['A.7.7', 'Clear desk and clear screen'],
  ['A.7.8', 'Equipment siting and protection'],
  ['A.7.9', 'Security of assets off-premises'],
  ['A.7.10', 'Storage media'],
  ['A.7.11', 'Supporting utilities'],
  ['A.7.12', 'Cabling security'],
  ['A.7.13', 'Equipment maintenance'],
  ['A.7.14', 'Secure disposal or re-use of equipment'],
  ['A.8.1', 'User endpoint devices'],
  ['A.8.2', 'Privileged access rights'],
  ['A.8.3', 'Information access restriction'],
  ['A.8.4', 'Access to source code'],
  ['A.8.5', 'Secure authentication'],
  ['A.8.6', 'Capacity management'],
  ['A.8.7', 'Protection against malware'],
  ['A.8.8', 'Management of technical vulnerabilities'],
  ['A.8.9', 'Configuration management'],
  ['A.8.10', 'Information deletion'],
  ['A.8.11', 'Data masking'],
  ['A.8.12', 'Data leakage prevention'],
  ['A.8.13', 'Information backup'],
  ['A.8.14', 'Redundancy of information processing facilities'],
  ['A.8.15', 'Logging'],
  ['A.8.16', 'Monitoring activities'],
  ['A.8.17', 'Clock synchronization'],
  ['A.8.18', 'Use of privileged utility programs'],
  ['A.8.19', 'Installation of software on operational systems'],
  ['A.8.20', 'Networks security'],
  ['A.8.21', 'Security of network services'],
  ['A.8.22', 'Segregation of networks'],
  ['A.8.23', 'Web filtering'],
  ['A.8.24', 'Use of cryptography'],
  ['A.8.25', 'Secure development life cycle'],
  ['A.8.26', 'Application security requirements'],
  ['A.8.27', 'Secure system architecture and engineering principles'],
  ['A.8.28', 'Secure coding'],
  ['A.8.29', 'Security testing in development and acceptance'],
  ['A.8.30', 'Outsourced development'],
  ['A.8.31', 'Separation of development, test and production environments'],
  ['A.8.32', 'Change management'],
  ['A.8.33', 'Test information'],
  ['A.8.34', 'Protection of information systems during audit testing'],
];

const iso37301: [string, string][] = [
  ['4.1', 'Verstehen der Organisation und ihres Kontextes'],
  ['4.2', 'Erfordernisse und Erwartungen interessierter Parteien'],
  ['4.3', 'Anwendungsbereich des CMS'],
  ['4.4', 'Compliance-Managementsystem'],
  ['4.5', 'Compliance-Verpflichtungen'],
  ['4.6', 'Compliance-Risikobeurteilung'],
  ['5.1', 'Führung und Verpflichtung / Compliance-Kultur'],
  ['5.2', 'Compliance-Politik'],
  ['5.3', 'Rollen, Verantwortlichkeiten und Befugnisse / Compliance-Funktion'],
  ['6.1', 'Maßnahmen zum Umgang mit Risiken und Chancen'],
  ['6.2', 'Compliance-Ziele und Planung'],
  ['6.3', 'Planung von Änderungen'],
  ['7.2', 'Kompetenz / Schulung'],
  ['7.3', 'Bewusstsein'],
  ['7.4', 'Kommunikation'],
  ['7.5', 'Dokumentierte Information'],
  ['8.1', 'Betriebliche Planung und Steuerung'],
  ['8.2', 'Festlegen von Kontrollen und Verfahren'],
  ['8.3', 'Äußern von Bedenken (Hinweisgebersystem)'],
  ['8.4', 'Untersuchungsprozesse'],
  ['9.1', 'Überwachung, Messung, Analyse und Bewertung'],
  ['9.2', 'Internes Audit'],
  ['9.3', 'Managementbewertung'],
  ['10.1', 'Fortlaufende Verbesserung'],
  ['10.2', 'Nichtkonformität und Korrekturmaßnahmen'],
];

export const isoCatalog: IsoRef[] = [
  ...iso9001.map(([clause, title]) => ({ id: `9001:${clause}`, standard: 'ISO 9001' as const, clause, title })),
  ...iso27001.map(([clause, title]) => ({ id: `27001:${clause}`, standard: 'ISO 27001' as const, clause, title })),
  ...annexA.map(([clause, title]) => ({ id: `27001:${clause}`, standard: 'ISO 27001' as const, clause, title })),
  ...iso37301.map(([clause, title]) => ({ id: `37301:${clause}`, standard: 'ISO 37301' as const, clause, title })),
];

export const isoById = new Map(isoCatalog.map((r) => [r.id, r]));

export function isoLabel(id: string): string {
  const r = isoById.get(id);
  return r ? `${r.standard} ${r.clause}` : id;
}
