// Demo data so the prototype is explorable right away.
import type { Control, EntityKind, EntityMap, Kpi, Opportunity, ProcessModel, Risk, Role, User } from './types';
import { blankEntity, emptyAssignment, now } from './logic';
import { accessManagementXml, purchaseToPayXml } from './bpmn/templates';

function make<K extends EntityKind>(kind: K, code: string, title: string, patch: Partial<EntityMap[K]>): EntityMap[K] {
  return { ...blankEntity(kind, code, title), id: code, ...patch };
}

export function seedData() {
  const user: User[] = [
    make('user', 'U-001', 'Daniel Becker', { email: 'd.becker@example.com', department: 'IT', jobTitle: 'Systemadministrator', systemRoles: ['admin'] }),
    make('user', 'U-002', 'Dr. Anna Berger', { email: 'a.berger@example.com', department: 'Einkauf', jobTitle: 'Leiterin Einkauf', systemRoles: ['process-modeler', 'org-manager'] }),
    make('user', 'U-003', 'Martin Huber', { email: 'm.huber@example.com', department: 'Einkauf', jobTitle: 'Senior Einkäufer', systemRoles: ['reader'] }),
    make('user', 'U-004', 'Sabine Klein', { email: 's.klein@example.com', department: 'Einkauf', jobTitle: 'Einkäuferin', systemRoles: ['reader'] }),
    make('user', 'U-005', 'Katrin Wagner', { email: 'k.wagner@example.com', department: 'Finanzen', jobTitle: 'Teamleiterin Kreditoren', systemRoles: ['control-owner'] }),
    make('user', 'U-006', 'Tobias Roth', { email: 't.roth@example.com', department: 'Finanzen', jobTitle: 'Kreditorenbuchhalter', systemRoles: ['reader'] }),
    make('user', 'U-007', 'Lena Schmid', { email: 'l.schmid@example.com', department: 'Recht & Compliance', jobTitle: 'Chief Compliance Officer', systemRoles: ['compliance', 'risk-manager'] }),
    make('user', 'U-008', 'Jonas Neumann', { email: 'j.neumann@example.com', department: 'IT / ISMS', jobTitle: 'Informationssicherheitsbeauftragter', systemRoles: ['grc-manager'] }),
    make('user', 'U-009', 'Petra Yilmaz', { email: 'p.yilmaz@example.com', department: 'Logistik', jobTitle: 'Leiterin Wareneingang', systemRoles: ['kpi-owner'] }),
    make('user', 'U-010', 'Frank Weber', { email: 'f.weber@example.com', department: 'Geschäftsführung', jobTitle: 'Geschäftsführer', systemRoles: ['reader'] }),
    make('user', 'U-011', 'Claudia Hoffmann', { email: 'c.hoffmann@example.com', department: 'Vertrieb', jobTitle: 'Bereichsleiterin Vertrieb', systemRoles: ['reader'] }),
    make('user', 'U-012', 'Ralf Krüger', { email: 'r.krueger@example.com', department: 'Interne Revision', jobTitle: 'Interner Revisor', systemRoles: ['auditor'] }),
    make('user', 'U-013', 'Miriam Lang', { email: 'm.lang@example.com', department: 'Qualitätsmanagement', jobTitle: 'Qualitätsmanagerin', systemRoles: ['grc-manager'] }),
    make('user', 'U-014', 'Extern: Datenschutz GmbH', { email: 'dsb@datenschutz-gmbh.example', department: 'extern', jobTitle: 'Externer DSB', systemRoles: ['reader'], validUntil: '2027-12-31' }),
  ];

  const holder = (userId: string, since: string) => ({ userId, function: 'Inhaber' as const, since, inducted: true });
  const deputy = (userId: string, since: string, inducted: boolean) => ({ userId, function: 'Stellvertretung' as const, since, inducted });
  const reviewed = { version: '1.0', status: 'Freigegeben', lastReview: '2026-01-15', nextReview: '2027-01-15' };

  const role: Role[] = [
    make('role', 'RO-001', 'Bedarfsträger', {
      ...reviewed,
      orgUnit: 'Generic',
      description: 'Alle Mitarbeitenden, die Waren oder Dienstleistungen anfordern.',
      responsibilities: 'Erfasst Bedarfe vollständig und sachlich korrekt.',
      competencies: 'Kenntnis der Beschaffungsrichtlinie',
      trainings: 'Beschaffungsrichtlinie (jährlich)',
      roleOwnerUserId: 'U-002',
      reportsToFunctionalRoleId: 'RO-002',
    }),
    make('role', 'RO-002', 'Kostenstellenverantwortlicher', {
      ...reviewed,
      roleType: 'Führungsrolle',
      orgUnit: 'Generic',
      responsibilities: 'Genehmigt Bedarfsanforderungen im Rahmen des Budgets.',
      authorities: 'Freigabe bis 25.000 EUR gemäß Unterschriftenregelung',
      members: [holder('U-011', '2021-04-01')],
      roleOwnerUserId: 'U-010',
      reportsToFunctionalRoleId: 'RO-010',
      reportsToDisciplinaryRoleId: 'RO-010',
      incompatibleRoleIds: ['RO-003'],
    }),
    make('role', 'RO-003', 'Einkäufer', {
      ...reviewed,
      orgUnit: 'Operation',
      responsibilities: 'Holt Angebote ein, verhandelt, löst Bestellungen aus.',
      authorities: 'Bestellungen im genehmigten Rahmen',
      competencies: 'Vertragsrecht, Verhandlungsführung',
      trainings: 'Anti-Korruption (jährlich), IS-Awareness',
      members: [holder('U-003', '2019-03-01'), holder('U-004', '2023-09-01'), deputy('U-006', '2025-02-01', false)],
      roleOwnerUserId: 'U-002',
      reportsToFunctionalRoleId: 'RO-004',
      reportsToDisciplinaryRoleId: 'RO-004',
      complianceRelevant: true,
      incompatibleRoleIds: ['RO-002', 'RO-005'],
      isoRefs: ['9001:5.3', '37301:5.3', '27001:A.5.3'],
    }),
    make('role', 'RO-004', 'Leitung Einkauf', {
      ...reviewed,
      roleType: 'Führungsrolle',
      orgUnit: 'Operation',
      responsibilities: 'Prozessverantwortung Beschaffung, Lieferantenmanagement.',
      authorities: 'Vergabeentscheidungen > 25.000 EUR',
      members: [holder('U-002', '2018-01-01'), deputy('U-003', '2020-01-01', true)],
      roleOwnerUserId: 'U-010',
      reportsToFunctionalRoleId: 'RO-010',
      reportsToDisciplinaryRoleId: 'RO-010',
      isoRefs: ['9001:5.3', '9001:8.4'],
    }),
    make('role', 'RO-005', 'Kreditorenbuchhaltung', {
      ...reviewed,
      orgUnit: 'Finance and Admin',
      responsibilities: 'Rechnungsprüfung, Zahlungsfreigabe (Vier-Augen-Prinzip).',
      members: [holder('U-005', '2017-06-01'), holder('U-006', '2022-01-01')],
      roleOwnerUserId: 'U-005',
      incompatibleRoleIds: ['RO-003'],
      reportsToDisciplinaryRoleId: 'RO-010',
    }),
    make('role', 'RO-006', 'Compliance Officer', {
      ...reviewed,
      roleType: 'Beauftragter',
      mandatory: true,
      orgUnit: 'Business Enablement',
      description: 'Compliance-Funktion gemäß ISO 37301 5.3.2.',
      responsibilities: 'Überwacht Compliance-Verpflichtungen, führt Geschäftspartnerprüfungen durch, berichtet an Geschäftsleitung.',
      authorities: 'Veto bei Compliance-Verstößen, uneingeschränktes Informationsrecht',
      members: [holder('U-007', '2020-07-01')],
      roleOwnerUserId: 'U-010',
      complianceRelevant: true,
      appointmentRequired: true,
      appointedAt: '2020-07-01',
      appointedByUserId: 'U-010',
      appointmentDocument: 'Bestellungsschreiben CO 2020-07 (DMS: COMP-ORG-001)',
      reportsToFunctionalRoleId: 'RO-010',
      reportsToDisciplinaryRoleId: 'RO-010',
      isoRefs: ['37301:5.3', '37301:5.1'],
    }),
    make('role', 'RO-007', 'Informationssicherheitsbeauftragter (ISB)', {
      ...reviewed,
      roleType: 'Beauftragter',
      mandatory: true,
      orgUnit: 'Technology',
      responsibilities: 'Steuert das ISMS, bewertet IS-Risiken, berichtet an die Geschäftsleitung.',
      members: [holder('U-008', '2022-02-01'), deputy('U-001', '2023-01-01', true)],
      roleOwnerUserId: 'U-010',
      complianceRelevant: true,
      appointmentRequired: true,
      appointedAt: '2022-02-01',
      appointedByUserId: 'U-010',
      appointmentDocument: 'Bestellung ISB (DMS: ISMS-ORG-002)',
      reportsToFunctionalRoleId: 'RO-010',
      reportsToDisciplinaryRoleId: 'RO-010',
      incompatibleRoleIds: ['RO-009'],
      isoRefs: ['27001:5.3', '27001:A.5.2'],
    }),
    make('role', 'RO-008', 'Wareneingang / Lager', {
      ...reviewed,
      orgUnit: 'Operation',
      responsibilities: 'Prüft Lieferungen auf Menge, Qualität und Beschädigung.',
      members: [holder('U-009', '2016-05-01')],
      roleOwnerUserId: 'U-009',
    }),
    make('role', 'RO-009', 'IT-Administration', {
      ...reviewed,
      orgUnit: 'Technology',
      responsibilities: 'Richtet Berechtigungen ein und entzieht sie.',
      incompatibleRoleIds: ['RO-007'],
      members: [holder('U-001', '2015-10-01')],
      roleOwnerUserId: 'U-008',
      complianceRelevant: true,
      isoRefs: ['27001:A.8.2'],
    }),
    make('role', 'RO-010', 'Geschäftsführung', {
      ...reviewed,
      roleType: 'Führungsrolle',
      mandatory: true,
      orgUnit: 'Generic',
      reportsToFunctionalRoleId: 'n/a',
      reportsToDisciplinaryRoleId: 'n/a',
      responsibilities: 'Oberste Leitung: Verantwortung für die Managementsysteme, Politik, Ressourcen, Managementbewertung.',
      members: [holder('U-010', '2014-01-01')],
      isoRefs: ['9001:5.1', '27001:5.1', '37301:5.1'],
    }),
    make('role', 'RO-011', 'Qualitätsmanagementbeauftragter (QMB)', {
      ...reviewed,
      roleType: 'Beauftragter',
      mandatory: true,
      orgUnit: 'Business Enablement',
      responsibilities: 'Sicherstellung der Konformität des QMS, Berichterstattung über die Leistung des QMS (ISO 9001 5.3).',
      members: [holder('U-013', '2021-01-01')],
      roleOwnerUserId: 'U-010',
      appointmentRequired: true,
      appointedAt: '2021-01-01',
      appointedByUserId: 'U-010',
      reportsToFunctionalRoleId: 'RO-010',
      reportsToDisciplinaryRoleId: 'RO-010',
      isoRefs: ['9001:5.3'],
    }),
    make('role', 'RO-012', 'Datenschutzbeauftragter', {
      version: '0.9',
      status: 'In Prüfung',
      nextReview: '2026-11-30',
      roleType: 'Beauftragter',
      mandatory: true,
      orgUnit: 'Other',
      responsibilities: 'Aufgaben nach Art. 39 DSGVO; Beratung und Überwachung der Einhaltung des Datenschutzes.',
      members: [holder('U-014', '2024-01-01')],
      roleOwnerUserId: 'U-007',
      appointmentRequired: true,
      appointedByUserId: 'U-010',
      reportsToFunctionalRoleId: 'RO-010',
      isoRefs: ['27001:A.5.34'],
    }),
    make('role', 'RO-013', 'Ausfuhrverantwortlicher', {
      ...reviewed,
      roleType: 'Beauftragter',
      mandatory: true,
      orgUnit: 'Business Enablement',
      description: 'Pflichtrolle nach Außenwirtschaftsrecht (Mitglied der Geschäftsleitung, gegenüber dem BAFA benannt).',
      responsibilities: 'Verantwortet die Einhaltung des Exportkontrollrechts (AWG/AWV, EU-Dual-Use-VO), Sanktionslistenprüfung.',
      members: [holder('U-010', '2019-01-01'), deputy('U-007', '2021-03-01', true)],
      roleOwnerUserId: 'U-007',
      appointmentRequired: true,
      appointedAt: '2019-01-01',
      appointedByUserId: 'U-010',
      appointmentDocument: 'Benennung gegenüber BAFA (DMS: EXP-ORG-001)',
      reportsToFunctionalRoleId: 'n/a',
      reportsToDisciplinaryRoleId: 'n/a',
      isoRefs: ['37301:4.5'],
    }),
    make('role', 'RO-014', 'Compliance-Komitee', {
      ...reviewed,
      roleType: 'Gremium',
      orgUnit: 'Generic',
      description: 'Quartalsweises Gremium aus GF, Compliance Officer, ISB und QMB.',
      responsibilities: 'Bewertet Compliance-, IS- und Qualitätsrisiken, beschließt Maßnahmen.',
      members: [holder('U-010', '2022-01-01'), holder('U-007', '2022-01-01'), holder('U-008', '2022-01-01'), holder('U-013', '2022-01-01')],
      roleOwnerUserId: 'U-007',
      reportsToFunctionalRoleId: 'RO-010',
      isoRefs: ['37301:9.3', '37301:5.1'],
    }),
  ];

  const risk: Risk[] = [
    make('risk', 'R-001', 'Bestellung ohne gültige Genehmigung', {
      category: 'Finanziell',
      cause: 'Umgehung des Freigabeworkflows, fehlende Systemsperre',
      consequence: 'Budgetüberschreitung, unberechtigte Verpflichtungen',
      likelihood: 3,
      impact: 4,
      residualLikelihood: 1,
      residualImpact: 4,
      ownerRoleId: 'RO-004',
      status: 'In Behandlung',
      treatment: 'Reduzieren',
      treatmentPlan: 'Systemseitige Freigabesperre, Vier-Augen-Prinzip',
      isoRefs: ['9001:6.1', '9001:8.4'],
    }),
    make('risk', 'R-002', 'Korruption / Vorteilsnahme bei Vergabe', {
      category: 'Compliance',
      cause: 'Interessenkonflikte, intransparente Vergabeentscheidungen',
      consequence: 'Strafrechtliche Konsequenzen (§§ 299 ff. StGB), Reputationsschaden',
      complianceObligation: 'StGB §299, Verhaltenskodex',
      interestedParties: 'Behörden, Kunden, Wettbewerber',
      likelihood: 2,
      impact: 5,
      residualLikelihood: 1,
      residualImpact: 5,
      ownerRoleId: 'RO-006',
      status: 'In Behandlung',
      treatmentPlan: 'Vergabedokumentation, Interessenkonflikterklärung, Schulung',
      isoRefs: ['37301:4.6', '37301:4.5'],
    }),
    make('risk', 'R-003', 'Lieferant mit unzureichender Informationssicherheit', {
      category: 'Informationssicherheit',
      cause: 'Keine IS-Anforderungen im Vertrag, fehlende Lieferantenbewertung',
      consequence: 'Datenabfluss, Lieferkettenangriff',
      affectedAssets: 'Kunden- und Konstruktionsdaten',
      protectionGoals: ['Vertraulichkeit', 'Integrität'],
      likelihood: 3,
      impact: 4,
      residualLikelihood: 2,
      residualImpact: 3,
      ownerRoleId: 'RO-007',
      status: 'Bewertet',
      isoRefs: ['27001:6.1.2', '27001:A.5.19', '27001:A.5.21'],
    }),
    make('risk', 'R-004', 'Doppelte oder fehlerhafte Zahlung', {
      category: 'Finanziell',
      cause: 'Manuelle Rechnungserfassung, fehlender 3-Way-Match',
      consequence: 'Finanzieller Verlust',
      likelihood: 3,
      impact: 3,
      residualLikelihood: 1,
      residualImpact: 3,
      ownerRoleId: 'RO-005',
      status: 'In Behandlung',
      isoRefs: ['9001:6.1'],
    }),
    make('risk', 'R-005', 'Mangelhafte Ware wird angenommen', {
      category: 'Qualität',
      cause: 'Keine/unzureichende Wareneingangsprüfung',
      consequence: 'Fehler im Endprodukt, Reklamationen',
      likelihood: 3,
      impact: 3,
      residualLikelihood: 2,
      residualImpact: 2,
      ownerRoleId: 'RO-008',
      status: 'Bewertet',
      isoRefs: ['9001:8.4', '9001:8.6', '9001:8.7'],
    }),
    make('risk', 'R-006', 'Überberechtigungen / verwaiste Accounts', {
      category: 'Informationssicherheit',
      cause: 'Fehlende Rezertifizierung, kein Leaver-Prozess',
      consequence: 'Unbefugter Zugriff auf vertrauliche Daten',
      protectionGoals: ['Vertraulichkeit', 'Integrität'],
      likelihood: 4,
      impact: 4,
      residualLikelihood: 2,
      residualImpact: 3,
      ownerRoleId: 'RO-007',
      status: 'In Behandlung',
      isoRefs: ['27001:6.1.2', '27001:A.5.18', '27001:A.8.2'],
    }),
  ];

  const opportunity: Opportunity[] = [
    make('opportunity', 'CH-001', 'Bündelung von Bedarfen (Rahmenverträge)', {
      category: 'Effizienz',
      benefit: 'Preisvorteile 5–8 %, weniger Bestellvorgänge',
      likelihood: 4,
      benefitScore: 4,
      ownerRoleId: 'RO-004',
    }),
    make('opportunity', 'CH-002', 'Automatisierte Rechnungsverarbeitung (OCR/E-Rechnung)', {
      category: 'Innovation',
      benefit: 'Kürzere Durchlaufzeit, Skontonutzung',
      likelihood: 3,
      benefitScore: 4,
      ownerRoleId: 'RO-005',
    }),
  ];

  const control: Control[] = [
    make('control', 'K-001', 'Systemseitige Freigabe von Bedarfsanforderungen', {
      objective: 'Nur genehmigte Bedarfe werden bestellt.',
      controlType: 'Präventiv',
      automation: 'Automatisiert',
      frequency: 'Ereignisbezogen',
      keyControl: true,
      ownerRoleId: 'RO-004',
      executorRoleId: 'RO-002',
      evidence: 'Workflow-Log im ERP',
      implementation: 'Umgesetzt',
      designEffectiveness: 'Wirksam',
      operatingEffectiveness: 'Wirksam',
      lastTest: '2026-03-15',
      nextTest: '2027-03-15',
      mitigatesRiskIds: ['R-001'],
      isoRefs: ['9001:8.4'],
    }),
    make('control', 'K-002', 'Vier-Augen-Prinzip Vergabeentscheidung', {
      objective: 'Vergaben > 25 TEUR werden durch zwei Personen entschieden und dokumentiert.',
      controlType: 'Präventiv',
      automation: 'Manuell',
      keyControl: true,
      ownerRoleId: 'RO-004',
      executorRoleId: 'RO-003',
      evidence: 'Vergabevermerk',
      annexA: ['A.5.3'],
      implementation: 'Umgesetzt',
      designEffectiveness: 'Wirksam',
      operatingEffectiveness: 'Eingeschränkt wirksam',
      lastTest: '2026-02-01',
      testResult: '2 von 25 Stichproben ohne Zweitunterschrift.',
      mitigatesRiskIds: ['R-002', 'R-001'],
      isoRefs: ['37301:8.2'],
    }),
    make('control', 'K-003', 'Geschäftspartnerprüfung (Sanktionslisten / Integrity Check)', {
      objective: 'Keine Geschäftsbeziehungen mit sanktionierten oder unzuverlässigen Partnern.',
      controlType: 'Präventiv',
      automation: 'Teilautomatisiert',
      ownerRoleId: 'RO-006',
      executorRoleId: 'RO-003',
      evidence: 'Screening-Report',
      implementation: 'Umgesetzt',
      mitigatesRiskIds: ['R-002'],
      isoRefs: ['37301:8.2', '37301:4.6'],
    }),
    make('control', 'K-004', 'IS-Lieferantenbewertung & vertragliche IS-Anforderungen', {
      objective: 'Lieferanten mit Datenzugriff erfüllen definierte IS-Mindestanforderungen.',
      controlType: 'Präventiv',
      automation: 'Manuell',
      ownerRoleId: 'RO-007',
      executorRoleId: 'RO-003',
      evidence: 'Lieferanten-Fragebogen, NDA, AV-Vertrag',
      annexA: ['A.5.19', 'A.5.20', 'A.5.21', 'A.5.22'],
      soaJustification: 'Erforderlich wegen Weitergabe vertraulicher Daten an Lieferanten.',
      implementation: 'Teilweise umgesetzt',
      mitigatesRiskIds: ['R-003'],
    }),
    make('control', 'K-005', '3-Way-Match (Bestellung / Wareneingang / Rechnung)', {
      objective: 'Nur berechtigte Rechnungen werden bezahlt.',
      controlType: 'Detektiv',
      automation: 'Automatisiert',
      keyControl: true,
      ownerRoleId: 'RO-005',
      executorRoleId: 'RO-005',
      implementation: 'Umgesetzt',
      designEffectiveness: 'Wirksam',
      operatingEffectiveness: 'Wirksam',
      lastTest: '2026-06-30',
      mitigatesRiskIds: ['R-004'],
    }),
    make('control', 'K-006', 'Wareneingangsprüfung nach Prüfplan', {
      objective: 'Fehlerhafte Ware wird erkannt und gesperrt.',
      controlType: 'Detektiv',
      automation: 'Manuell',
      ownerRoleId: 'RO-004',
      executorRoleId: 'RO-008',
      evidence: 'WE-Prüfprotokoll',
      implementation: 'Umgesetzt',
      mitigatesRiskIds: ['R-005'],
      isoRefs: ['9001:8.6'],
    }),
    make('control', 'K-007', 'Halbjährliche Rezertifizierung von Berechtigungen', {
      objective: 'Berechtigungen entsprechen dem Need-to-know-Prinzip.',
      controlType: 'Detektiv',
      automation: 'IT-abhängig manuell',
      frequency: 'Halbjährlich',
      keyControl: true,
      ownerRoleId: 'RO-007',
      executorRoleId: 'RO-002',
      annexA: ['A.5.15', 'A.5.18', 'A.8.2'],
      implementation: 'Teilweise umgesetzt',
      mitigatesRiskIds: ['R-006'],
    }),
  ];

  const kpi: Kpi[] = [
    make('kpi', 'KPI-001', 'Bestellungen mit gültiger Freigabe', {
      objective: 'Ordnungsgemäße Beschaffung',
      formula: 'freigegebene Bestellungen / alle Bestellungen × 100',
      unit: '%',
      target: 100,
      warning: 98,
      critical: 95,
      dataSource: 'ERP',
      ownerRoleId: 'RO-004',
      measurements: [
        { date: '2026-06-30', value: 97.5 },
        { date: '2026-07-31', value: 98.8 },
        { date: '2026-08-31', value: 99.4 },
      ],
    }),
    make('kpi', 'KPI-002', 'Durchlaufzeit Bedarf bis Bestellung', {
      objective: 'Effiziente Beschaffung',
      formula: 'Ø Tage zwischen Anforderung und Bestellung',
      unit: 'Tage',
      direction: 'lower',
      target: 5,
      warning: 7,
      critical: 10,
      dataSource: 'ERP',
      ownerRoleId: 'RO-004',
      measurements: [
        { date: '2026-06-30', value: 8.1 },
        { date: '2026-07-31', value: 7.4 },
        { date: '2026-08-31', value: 6.2 },
      ],
    }),
    make('kpi', 'KPI-003', 'Lieferanten mit gültiger IS-/Compliance-Bewertung', {
      objective: 'Sichere Lieferkette',
      formula: 'bewertete kritische Lieferanten / alle kritischen Lieferanten × 100',
      unit: '%',
      target: 100,
      warning: 90,
      critical: 75,
      ownerRoleId: 'RO-007',
      measurements: [
        { date: '2026-03-31', value: 62 },
        { date: '2026-06-30', value: 71 },
      ],
      isoRefs: ['27001:9.1', '37301:9.1'],
    }),
    make('kpi', 'KPI-004', 'Reklamationsquote Wareneingang', {
      objective: 'Qualität zugekaufter Teile',
      formula: 'reklamierte Lieferungen / alle Lieferungen × 100',
      unit: '%',
      direction: 'lower',
      target: 1,
      warning: 2,
      critical: 3,
      ownerRoleId: 'RO-008',
      measurements: [
        { date: '2026-07-31', value: 1.8 },
        { date: '2026-08-31', value: 2.4 },
      ],
    }),
    make('kpi', 'KPI-005', 'Abgeschlossene Rezertifizierungen', {
      unit: '%',
      target: 100,
      warning: 95,
      critical: 85,
      ownerRoleId: 'RO-007',
      measurements: [{ date: '2026-06-30', value: 88 }],
      isoRefs: ['27001:9.1'],
    }),
  ];

  const a = (patch: Partial<ReturnType<typeof emptyAssignment>>) => ({ ...emptyAssignment(), ...patch });

  const processes: ProcessModel[] = [
    {
      id: 'P-001',
      code: 'P-001',
      title: 'Beschaffung (Purchase-to-Pay)',
      description: 'Von der Bedarfsanforderung bis zur Zahlung an den Lieferanten.',
      category: 'Kernprozess',
      ownerRoleId: 'RO-004',
      version: '1.2',
      status: 'Freigegeben',
      standards: ['ISO 9001', 'ISO 27001', 'ISO 37301'],
      nextReview: '2027-01-31',
      xml: purchaseToPayXml(),
      callLinks: {},
      assignments: {
        Task_Bedarf: a({ roles: [{ roleId: 'RO-001', raci: 'R' }], kpis: ['KPI-002'] }),
        Task_Genehmigen: a({
          roles: [
            { roleId: 'RO-002', raci: 'A' },
            { roleId: 'RO-003', raci: 'I' },
          ],
          risks: ['R-001'],
          controls: ['K-001'],
          kpis: ['KPI-001'],
        }),
        Sub_Lieferant: a({ roles: [{ roleId: 'RO-004', raci: 'A' }], opportunities: ['CH-001'] }),
        Task_Angebote: a({ roles: [{ roleId: 'RO-003', raci: 'R' }] }),
        Task_Vergleich: a({ roles: [{ roleId: 'RO-003', raci: 'R' }], opportunities: ['CH-001'] }),
        Task_LiefPruefung: a({
          roles: [
            { roleId: 'RO-003', raci: 'R' },
            { roleId: 'RO-006', raci: 'C' },
            { roleId: 'RO-007', raci: 'C' },
          ],
          risks: ['R-002', 'R-003'],
          controls: ['K-003', 'K-004'],
          kpis: ['KPI-003'],
        }),
        Task_Vergabe: a({
          roles: [
            { roleId: 'RO-003', raci: 'R' },
            { roleId: 'RO-004', raci: 'A' },
          ],
          risks: ['R-002'],
          controls: ['K-002'],
        }),
        Task_Bestellung: a({ roles: [{ roleId: 'RO-003', raci: 'R' }], risks: ['R-001'] }),
        Task_WE: a({ roles: [{ roleId: 'RO-008', raci: 'R' }], risks: ['R-005'], controls: ['K-006'], kpis: ['KPI-004'] }),
        Task_Rechnung: a({
          roles: [{ roleId: 'RO-005', raci: 'R' }],
          risks: ['R-004'],
          controls: ['K-005'],
          opportunities: ['CH-002'],
        }),
        Task_Zahlung: a({ roles: [{ roleId: 'RO-005', raci: 'A' }] }),
      },
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: 'P-002',
      code: 'P-002',
      title: 'Berechtigungsmanagement',
      description: 'Vergabe, Änderung und Rezertifizierung von Zugriffsrechten.',
      category: 'Unterstützungsprozess',
      ownerRoleId: 'RO-007',
      version: '1.0',
      status: 'In Prüfung',
      standards: ['ISO 27001'],
      nextReview: '2026-12-31',
      xml: accessManagementXml(),
      callLinks: {},
      assignments: {
        IAM_Antrag: a({ roles: [{ roleId: 'RO-001', raci: 'R' }] }),
        IAM_Genehmigung: a({ roles: [{ roleId: 'RO-002', raci: 'A' }], risks: ['R-006'] }),
        IAM_Einrichten: a({ roles: [{ roleId: 'RO-009', raci: 'R' }] }),
        IAM_Rezert: a({
          roles: [
            { roleId: 'RO-002', raci: 'R' },
            { roleId: 'RO-007', raci: 'A' },
          ],
          risks: ['R-006'],
          controls: ['K-007'],
          kpis: ['KPI-005'],
        }),
      },
      createdAt: now(),
      updatedAt: now(),
    },
  ];

  return { user, role, risk, opportunity, control, kpi, processes, currentUserId: 'U-001' };
}
